---

- name: Create the Systemd Unit file for the dovecot-exporter service
  template:
    src: dovecot_exporter.systemd.j2
    dest: /etc/systemd/system/dovecot_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd and restart dovecot_exporter
  when: ansible_service_mgr == "systemd"

- name: Create the Upstart Unit file for the dovecot-exporter service
  template:
    src: dovecot_exporter.upstart.j2
    dest: /etc/init/dovecot_exporter.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dovecot_exporter
  when: ansible_service_mgr == "upstart"

- name: Create the generic start-stop script for the dovecot-exporter service
  template:
    src: dovecot_exporter.service.j2
    dest: /etc/init.d/dovecot_exporter
    owner: root
    group: root
    mode: 0755
  notify: restart dovecot_exporter
  when: ansible_service_mgr not in [ "systemd", "upstart" ]
