---

- name: Set the Github API endpoint
  set_fact:
    _dovecot_exporter_github_api_url: |-
      {% if dovecot_exporter_release_tag == 'latest' %}
      https://api.github.com/repos/kumina/dovecot_exporter/releases/latest
      {% else %}
      https://api.github.com/repos/kumina/dovecot_exporter/releases/tags/{{ dovecot_exporter_release_tag }}
      {% endif %}

- name: Set the Github API token
  set_fact:
    _dovecot_exporter_github_api_token: "{{ lookup('env', 'GITHUB_API_TOKEN') }}"

- name: Fetch the dovecot-exporter release information from Github
  uri:
    url: "{{ _dovecot_exporter_github_api_url }}"
    method: GET
    headers:
      Authorization: "{% if _dovecot_exporter_github_api_token %}token {{ _dovecot_exporter_github_api_token }}{% endif %}"
  check_mode: no
  register: _dovecot_exporter_github_release
  until: |
    'status' in _dovecot_exporter_github_release
      and _dovecot_exporter_github_release['status'] == 200
  retries: 5
  delay: 15

- name: Get the tag of the latest dovecot-exporter Github release
  set_fact:
    dovecot_exporter_release_tag: "{{ _dovecot_exporter_github_release['json'] | json_query('tag_name') }}"
  when: dovecot_exporter_release_tag == "latest"

- name: Set the Github download URL for the dovecot-exporter release
  set_fact:
    dovecot_exporter_release_url: "{{ _dovecot_exporter_github_release['json'] | json_query(_dovecot_exporter_release_asset_url_query) }}"
  vars:
    _dovecot_exporter_release_asset_url_query: "assets[?name=='{{ hostvars[inventory_hostname] | dovecot_exporter_release_build(dovecot_exporter_release_tag) }}.tar.gz'] | [0].browser_download_url"  # noqa 204
